# Generated by Django 4.2.4 on 2023-08-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('participants', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accessibility', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link', models.URLField()),
            ],
        ),
    ]
