version: '3.9'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/APIWrapperBoredAPI
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${PG_PASSWORD}
      PGUSER: ${PG_USER}
    ports:
      - 127.0.0.1:${DB_PORT}:5432

volumes:
  db_data:
